import './styles/main.scss'
// import routes generated by Voie
import routes from 'voie-pages'
// progress bar
import NProgress from 'nprogress'
import { ViteSSG } from 'vite-ssg'
import installPlugins from './plugins'
import App from './App.vue'

export const createApp = ViteSSG(
  App,
  { routes },
  ({ app, router, isClient }) => {
    installPlugins(app)

    if (isClient) {
      router.beforeEach(() => { NProgress.start() })
      router.afterEach(() => { NProgress.done() })
    }
  },
)

if (typeof globalThis.navigator !== 'undefined' && 'serviceWorker' in globalThis.navigator) {
  globalThis.addEventListener('load', () => {
    globalThis.navigator.serviceWorker.register(
      process.env.NODE_ENV === 'production'
        ? '/sw.js'
        : '/dist/sw.js',
    )
  })
}
